#!/usr/bin/env python3
"""Validate editable CSV question packs and build the browser's static data file."""
import argparse
import csv
import datetime
import json
from pathlib import Path
import re
import unicodedata

ROOT = Path(__file__).resolve().parents[1]
TIERS = {10, 15, 30, 60, 85, 100}


def normalize(value):
    value = ''.join(c for c in unicodedata.normalize('NFD', value) if not '\u0300' <= c <= '\u036f')
    return re.sub(r'\s+', ' ', re.sub(r'[^a-z0-9\s]', ' ', value.lower())).strip()


def load_packs(folder):
    days = []
    for manifest in sorted(folder.glob('*/day.json')):
        day = json.loads(manifest.read_text(encoding='utf-8'))
        day_id = day['id']
        if datetime.date.fromisoformat(day_id).isoformat() != day_id or manifest.parent.name != day_id:
            raise ValueError(f'{manifest}: id must match its YYYY-MM-DD folder')
        if not isinstance(day.get('label'), str) or not day['label'].strip():
            raise ValueError(f'{manifest}: label is required')
        if len(day['questions']) != 7:
            raise ValueError(f'{manifest}: each day must contain exactly seven questions')
        questions = []
        for metadata in day['questions']:
            question = dict(metadata)
            filename = question.pop('csv')
            if Path(filename).name != filename or not filename.endswith('.csv'):
                raise ValueError(f'{manifest}: csv must be a filename in this day folder')
            if not isinstance(question.get('prompt'), str) or not question['prompt'].strip():
                raise ValueError(f'{manifest}: question prompt is required')
            source = manifest.parent / filename
            answers, owners = [], {}
            with source.open(encoding='utf-8-sig', newline='') as handle:
                reader = csv.DictReader(handle)
                if reader.fieldnames != ['ANSWER', 'Blurb', 'Worth']:
                    raise ValueError(f'{source}: expected headers ANSWER,Blurb,Worth')
                for row in reader:
                    location = f'{source}:{reader.line_num}'
                    if None in row or any(value is None for value in row.values()):
                        raise ValueError(f'{location}: expected exactly three CSV columns')
                    forms = [form.strip() for form in row['ANSWER'].split('|')]
                    if any(not normalize(form) for form in forms):
                        raise ValueError(f'{location}: answer and aliases cannot be empty')
                    try:
                        points = int(row['Worth'])
                    except ValueError:
                        raise ValueError(f'{location}: Worth must be an integer') from None
                    if points not in TIERS:
                        raise ValueError(f'{location}: Worth must be one of {sorted(TIERS)}')
                    for form in forms:
                        key = normalize(form)
                        if key in owners and owners[key] != reader.line_num:
                            raise ValueError(f'{location}: duplicate answer/alias {form!r}')
                        owners[key] = reader.line_num
                    answers.append({'points': points, 'forms': forms, 'note': row['Blurb'].strip()})
            if not answers:
                raise ValueError(f'{source}: at least one answer is required')
            question['answers'] = answers
            questions.append(question)
        days.append({'id': day_id, 'label': day['label'], 'questions': questions})
    if not days:
        raise ValueError(f'{folder}: no day.json manifests found')
    return days


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='validate without writing')
    args = parser.parse_args()
    try:
        days = load_packs(ROOT / 'question-packs')
    except (ValueError, KeyError, TypeError, OSError) as error:
        parser.exit(1, f'Question pack error: {error}\n')
    if not args.check:
        output = '// Generated by scripts/build_questions.py. Edit question-packs instead.\n'
        output += 'window.DIVE_DAYS = ' + json.dumps(days, ensure_ascii=True, indent=2) + ';\n'
        output += 'window.DIVE_QUESTIONS = window.DIVE_DAYS.at(-1).questions;\n'
        (ROOT / 'questions-days.js').write_text(output, encoding='utf-8')
    print(f'{"Validated" if args.check else "Built"} {len(days)} days, {sum(len(d["questions"]) for d in days)} questions.')


if __name__ == '__main__':
    main()
